/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardgame.Vue.GUI;

import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author mathieu
 */
public class InfoDialogSloubi extends javax.swing.JDialog {

    /**
     * Creates new form InfoDialog
     */
    private final String info;
    
    public InfoDialogSloubi(java.awt.Frame parent, boolean modal,String content) {
        super(parent, modal);
        initComponents();
        info = content;
        txtInfo.setText(info);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gs = ge.getScreenDevices();
        Dimension mySize = new Dimension(800,600);
        Dimension maxSize = new Dimension(500,500);
        for (int i  = 0; i < gs.length ; i++ ) {
            DisplayMode dm = gs[i].getDisplayMode();
            if (dm.getWidth() > maxSize.getWidth() && dm.getHeight() > maxSize.getHeight()) {
            maxSize.setSize(dm.getWidth(),dm.getHeight());
        }
            this.setPreferredSize(maxSize);
            this.pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        txtInfo.setColumns(10);
        txtInfo.setFont(new java.awt.Font("Monospaced", 3, 8)); // NOI18N
        txtInfo.setLineWrap(true);
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
